from __future__ import annotations
import os
import logging
from homeassistant.core import HomeAssistant
from homeassistant.config_entries import ConfigEntry
from homeassistant.helpers import entity_registry as er
from homeassistant.helpers.start import async_at_start
from .const import DOMAIN, CONF_EXCLUDE_FROM_RECORDER

_LOGGER = logging.getLogger(__name__)

PACKAGES_SUBDIR = "packages"
RECORDER_PACKAGE_FILENAME = "real_last_sensors_{entry_id}.yaml"
RECORDER_PACKAGE_TEMPLATE = """\
# Auto-generated by the Real Last Sensors integration.
# Delete this file or disable the option in the integration settings to stop excluding these entities.
recorder:
  exclude:
    entities:
{entity_lines}
"""


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Set up the integration."""
    await hass.config_entries.async_forward_entry_setups(entry, ["sensor"])
    entry.async_on_unload(entry.add_update_listener(_async_options_updated))

    async def _on_ha_start(_hass: HomeAssistant) -> None:
        await _sync_recorder_package(hass, entry)

    async_at_start(hass, _on_ha_start)
    return True


async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Unload a config entry."""
    unload_ok = await hass.config_entries.async_unload_platforms(entry, ["sensor"])
    return unload_ok


async def async_remove_entry(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Clean up recorder package file when entry is deleted."""
    await hass.async_add_executor_job(_delete_package_file, hass, entry.entry_id)


async def _async_options_updated(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Called when the user changes options — sync recorder package and reload."""
    await _sync_recorder_package(hass, entry)
    await hass.config_entries.async_reload(entry.entry_id)


async def _sync_recorder_package(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Write or delete the recorder exclusion package YAML for this entry."""
    exclude = entry.options.get(CONF_EXCLUDE_FROM_RECORDER, True)

    if exclude:
        entity_ids = _get_entry_entity_ids(hass, entry)
        if entity_ids:
            await hass.async_add_executor_job(
                _write_package_file, hass, entry.entry_id, entity_ids
            )
            await _purge_entity_history(hass, entity_ids)
    else:
        await hass.async_add_executor_job(
            _delete_package_file, hass, entry.entry_id
        )


def _get_entry_entity_ids(hass: HomeAssistant, entry: ConfigEntry) -> list[str]:
    """Return entity IDs registered for this config entry."""
    ent_reg = er.async_get(hass)
    return [
        e.entity_id
        for e in ent_reg.entities.values()
        if e.config_entry_id == entry.entry_id
    ]


def _write_package_file(
    hass: HomeAssistant, entry_id: str, entity_ids: list[str]
) -> None:
    """Write the recorder exclusion YAML package file (blocking I/O)."""
    packages_dir = os.path.join(hass.config.config_dir, PACKAGES_SUBDIR)
    os.makedirs(packages_dir, exist_ok=True)
    file_path = os.path.join(
        packages_dir, RECORDER_PACKAGE_FILENAME.format(entry_id=entry_id)
    )
    entity_lines = "\n".join(f"      - {eid}" for eid in sorted(entity_ids))
    content = RECORDER_PACKAGE_TEMPLATE.format(entity_lines=entity_lines)
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
    _LOGGER.debug("Wrote recorder exclusion package: %s", file_path)


def _delete_package_file(hass: HomeAssistant, entry_id: str) -> None:
    """Delete the recorder exclusion YAML package file (blocking I/O)."""
    file_path = os.path.join(
        hass.config.config_dir,
        PACKAGES_SUBDIR,
        RECORDER_PACKAGE_FILENAME.format(entry_id=entry_id),
    )
    if os.path.exists(file_path):
        os.remove(file_path)
        _LOGGER.debug("Deleted recorder exclusion package: %s", file_path)


async def _purge_entity_history(hass: HomeAssistant, entity_ids: list[str]) -> None:
    """Purge existing recorder history for the given entities."""
    try:
        await hass.services.async_call(
            "recorder",
            "purge_entities",
            {"entity_id": entity_ids, "keep_days": 0},
            blocking=False,
        )
    except Exception:  # noqa: BLE001
        pass  # recorder may not be loaded
