from __future__ import annotations
import os
import logging
from homeassistant.core import HomeAssistant, callback
from homeassistant.config_entries import ConfigEntry
from homeassistant.helpers import entity_registry as er
from homeassistant.helpers.event import async_track_entity_registry_updated_event
from homeassistant.helpers.start import async_at_start
from .const import (
    DOMAIN,
    CONF_EXCLUDE_FROM_RECORDER,
    CONF_SOURCE_ENTITY,
    CONF_SOURCE_ENTITIES,
    CONF_SENSOR_TYPES,
    SENSOR_TYPE_CHANGED,
    SENSOR_TYPE_SEEN,
)

_LOGGER = logging.getLogger(__name__)

TYPE_SUFFIXES = {
    SENSOR_TYPE_CHANGED: "last_changed",
    SENSOR_TYPE_SEEN: "last_seen",
}

PACKAGES_SUBDIR = "packages"
RECORDER_PACKAGE_FILENAME = "real_last_sensors_{entry_id}.yaml"
RECORDER_PACKAGE_TEMPLATE = """\
# Auto-generated by the Real Last Sensors integration.
# Delete this file or disable the option in the integration settings to stop excluding these entities.
recorder:
  exclude:
    entities:
{entity_lines}
"""


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Set up the integration."""
    _LOGGER.warning(
        "Setting up entry %s (title=%r, version=%s, data=%s)",
        entry.entry_id,
        entry.title,
        entry.version,
        dict(entry.data),
    )

    _cleanup_ghost_entities(hass)

    await hass.config_entries.async_forward_entry_setups(entry, ["sensor"])
    entry.async_on_unload(entry.add_update_listener(_async_options_updated))

    _register_source_rename_tracker(hass, entry)

    async def _on_ha_start(_hass: HomeAssistant) -> None:
        await _sync_recorder_package(hass, entry)

    async_at_start(hass, _on_ha_start)
    return True


def _entry_sources(entry: ConfigEntry) -> list[str]:
    sources = list(entry.data.get(CONF_SOURCE_ENTITIES, []))
    if not sources and CONF_SOURCE_ENTITY in entry.data:
        sources = [entry.data[CONF_SOURCE_ENTITY]]
    return sources


def _register_source_rename_tracker(
    hass: HomeAssistant, entry: ConfigEntry
) -> None:
    """Follow entity_id renames on the source entities and update the entry.

    Without this, renaming the source in HA's UI leaves our entry.data
    pointing at a now-nonexistent entity_id, which is how stale unique_ids
    and entity_ids ended up surviving every cleanup pass.
    """
    source_ids = _entry_sources(entry)
    if not source_ids:
        return

    @callback
    def _on_source_registry_update(event) -> None:
        data = event.data
        if data.get("action") != "update":
            return
        changes = data.get("changes") or {}
        if "entity_id" not in changes:
            return
        old_id = changes["entity_id"]
        new_id = data.get("entity_id")
        if not old_id or not new_id or old_id == new_id:
            return

        new_data = dict(entry.data)
        changed = False
        if CONF_SOURCE_ENTITIES in new_data and old_id in new_data[CONF_SOURCE_ENTITIES]:
            new_data[CONF_SOURCE_ENTITIES] = [
                new_id if e == old_id else e
                for e in new_data[CONF_SOURCE_ENTITIES]
            ]
            changed = True
        if (
            CONF_SOURCE_ENTITY in new_data
            and new_data.get(CONF_SOURCE_ENTITY) == old_id
        ):
            new_data[CONF_SOURCE_ENTITY] = new_id
            changed = True

        if changed:
            _LOGGER.warning(
                "Entry %s: source renamed %s -> %s; updating and reloading",
                entry.entry_id,
                old_id,
                new_id,
            )
            hass.config_entries.async_update_entry(entry, data=new_data)
            hass.async_create_task(
                hass.config_entries.async_reload(entry.entry_id)
            )

    entry.async_on_unload(
        async_track_entity_registry_updated_event(
            hass, source_ids, _on_source_registry_update
        )
    )


async def async_migrate_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Migrate old config entries.

    v1 -> v2: older releases generated entity_ids from upstream display names,
    which could go stale after source renames. Wipe the registry entries once
    so they get recreated with the new slug-based scheme; HA preserves future
    user renames on its own.
    """
    if entry.version > 2:
        return False

    if entry.version < 2:
        ent_reg = er.async_get(hass)
        removed = 0
        for reg in list(ent_reg.entities.values()):
            if reg.platform == DOMAIN and reg.config_entry_id == entry.entry_id:
                ent_reg.async_remove(reg.entity_id)
                removed += 1
        _LOGGER.info(
            "Migrated entry %s to v2 (removed %d legacy entity registry rows)",
            entry.entry_id,
            removed,
        )
        hass.config_entries.async_update_entry(entry, version=2)

    return True


def _cleanup_ghost_entities(hass: HomeAssistant) -> None:
    """Delete registry rows that no live config entry expects.

    A row is considered a ghost if either:
      * it has no config_entry_id (orphaned),
      * its unique_id isn't among those currently expected by any config
        entry, where the expected set is derived only from sources that
        still exist in the entity registry. Sources that were renamed in
        the upstream integration no longer exist, so any unique_id that
        was derived from them is treated as stale and removed.
    """
    ent_reg = er.async_get(hass)
    expected: set[str] = set()
    for entry in hass.config_entries.async_entries(DOMAIN):
        types = entry.data.get(CONF_SENSOR_TYPES, [SENSOR_TYPE_CHANGED])
        for src in _entry_sources(entry):
            if ent_reg.async_get(src) is None:
                _LOGGER.warning(
                    "Entry %s: source %s is not in the entity registry "
                    "(renamed or removed upstream). Its rows will be wiped.",
                    entry.entry_id,
                    src,
                )
                continue
            for t in types:
                expected.add(f"{src.replace('.', '_')}_{TYPE_SUFFIXES[t]}")

    our_rows = [r for r in ent_reg.entities.values() if r.platform == DOMAIN]
    _LOGGER.warning(
        "Ghost cleanup: %d registry rows under %s; expected unique_ids=%s",
        len(our_rows),
        DOMAIN,
        sorted(expected),
    )
    for reg in our_rows:
        _LOGGER.warning(
            "  row entity_id=%s unique_id=%s config_entry_id=%s name=%r original_name=%r",
            reg.entity_id,
            reg.unique_id,
            reg.config_entry_id,
            reg.name,
            reg.original_name,
        )

    for reg in list(our_rows):
        if reg.config_entry_id is None or reg.unique_id not in expected:
            _LOGGER.warning(
                "Removing ghost entity %s (unique_id=%s, config_entry_id=%s)",
                reg.entity_id,
                reg.unique_id,
                reg.config_entry_id,
            )
            ent_reg.async_remove(reg.entity_id)


async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Unload a config entry."""
    unload_ok = await hass.config_entries.async_unload_platforms(entry, ["sensor"])
    return unload_ok


async def async_remove_entry(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Clean up registry entries and recorder package file when entry is deleted.

    Wiping registry entries here prevents HA from retaining orphans
    (config_entry_id=None) that could later be re-associated and resurface as
    stale entity_ids.
    """
    ent_reg = er.async_get(hass)
    for reg in list(ent_reg.entities.values()):
        if reg.platform == DOMAIN and reg.config_entry_id == entry.entry_id:
            ent_reg.async_remove(reg.entity_id)
    await hass.async_add_executor_job(_delete_package_file, hass, entry.entry_id)


async def _async_options_updated(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Called when the user changes options — sync recorder package and reload."""
    await _sync_recorder_package(hass, entry)
    await hass.config_entries.async_reload(entry.entry_id)


async def _sync_recorder_package(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Write or delete the recorder exclusion package YAML for this entry."""
    exclude = entry.options.get(CONF_EXCLUDE_FROM_RECORDER, True)

    if exclude:
        entity_ids = _get_entry_entity_ids(hass, entry)
        if entity_ids:
            await hass.async_add_executor_job(
                _write_package_file, hass, entry.entry_id, entity_ids
            )
            await _purge_entity_history(hass, entity_ids)
    else:
        await hass.async_add_executor_job(
            _delete_package_file, hass, entry.entry_id
        )


def _get_entry_entity_ids(hass: HomeAssistant, entry: ConfigEntry) -> list[str]:
    """Return entity IDs registered for this config entry."""
    ent_reg = er.async_get(hass)
    return [
        e.entity_id
        for e in ent_reg.entities.values()
        if e.config_entry_id == entry.entry_id
    ]


def _write_package_file(
    hass: HomeAssistant, entry_id: str, entity_ids: list[str]
) -> None:
    """Write the recorder exclusion YAML package file (blocking I/O)."""
    packages_dir = os.path.join(hass.config.config_dir, PACKAGES_SUBDIR)
    os.makedirs(packages_dir, exist_ok=True)
    file_path = os.path.join(
        packages_dir, RECORDER_PACKAGE_FILENAME.format(entry_id=entry_id)
    )
    entity_lines = "\n".join(f"      - {eid}" for eid in sorted(entity_ids))
    content = RECORDER_PACKAGE_TEMPLATE.format(entity_lines=entity_lines)
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
    _LOGGER.debug("Wrote recorder exclusion package: %s", file_path)


def _delete_package_file(hass: HomeAssistant, entry_id: str) -> None:
    """Delete the recorder exclusion YAML package file (blocking I/O)."""
    file_path = os.path.join(
        hass.config.config_dir,
        PACKAGES_SUBDIR,
        RECORDER_PACKAGE_FILENAME.format(entry_id=entry_id),
    )
    if os.path.exists(file_path):
        os.remove(file_path)
        _LOGGER.debug("Deleted recorder exclusion package: %s", file_path)


async def _purge_entity_history(hass: HomeAssistant, entity_ids: list[str]) -> None:
    """Purge existing recorder history for the given entities."""
    try:
        await hass.services.async_call(
            "recorder",
            "purge_entities",
            {"entity_id": entity_ids, "keep_days": 0},
            blocking=False,
        )
    except Exception:  # noqa: BLE001
        pass  # recorder may not be loaded
